### ISSUE TITLE
Fruit 기능 요약

### ISSUE THREAD

**Issue by sunghwan97** [glowisn/lab13_mimi_project#2]

**Comment by glowisn** [comment]
과일
1. 이름
2. 가격
3. 무게

1. CRUD - 예찬
2. 저장/읽어오기 - 예찬
3. 이름으로 검색 - 성환
4. 가격으로 검색 - 성환
5. 분석 - 예찬

**Comment by sunghwan97** [comment]
1. 구조체 정보(Fruit) - 예찬
1) 이름
2) 가격
3) 무게

**Comment by sunghwan97** [comment]
2. CRUD - 예찬

**Comment by sunghwan97** [comment]
3. 저장 / 읽어오기 - 성환

**Comment by sunghwan97** [comment]
4. 이름으로 검색 - 성환

**Comment by sunghwan97** [comment]
5. 분석 - 예찬

**Comment by sunghwan97** [comment]
6. 가장 비싼 과일 알려주기 - 성환

**Comment by sunghwan97** [comment]
7. 가장 싼 과일 알려주기 - 성환

**Comment by glowisn** [comment]
기능 개발 완료됨.
